### ISSUE TITLE
Question: desktop picture profile

### ISSUE THREAD

**Issue by clburlison** [gregneagle/profiles#1]
Hey Greg,

Do you know what the locked key actually does in your [desktop_picture](https://raw.githubusercontent.com/gregneagle/profiles/master/desktop_picture.mobileconfig) profile? To me it would give the user the ability to override this profile or not but in my tests, no matter the locked value, this profile will forcefully set the desktop picture. I have tested this profile on both Mavericks and Yosemite with the same results.

``` plist
     <key>PayloadVersion</key>
     <integer>1</integer>
     <key>locked</key>
     <true/>
     <key>override-picture-path</key>
     <string>/Library/Desktop Pictures/Abstract.jpg</string>
```

**Comment by gregneagle** [comment]
The profile behavior is entirely controlled by Apple's code and I have no more information than you.  I tested exactly one thing: that it set a desktop picture and prevented it from being changed.  You might look at the Profile Manager UI; if it implies the functionality you want then you might file a bug with Apple.

**Comment by clburlison** [comment]
Thanks! I'll look into the Profile Manager.
