### ISSUE TITLE
Disabling google auto update

### ISSUE THREAD

**Issue by vikaskedia** [gregneagle/profiles#2]
Even after installing the profile at: https://github.com/gregneagle/profiles/blob/master/autoupdate_disablers/disable_autoupdates_googlekeystone.mobileconfig

When chrome is started it says:
![image](https://user-images.githubusercontent.com/6703876/34481483-4eff57c4-ef67-11e7-9308-41b2ab3dc7e2.png)

I have confirmed that the profile is active:
![image](https://user-images.githubusercontent.com/6703876/34481508-6d92a948-ef67-11e7-9bd5-afe6c4ff16d1.png)

**Comment by gregneagle** [comment]
Addressed here: https://github.com/gregneagle/profiles/commit/fecc73d66fa17b6fa78b782904cb47cdc1913aeb

**Comment by gregneagle** [comment]
You might want to take a look at https://support.google.com/chrome/a/answer/7550274?hl=en
